[tool.poetry]
name = "PyCurlRunner"
version = "0.1.0"
description = "A project to process curls/parse commands from file/text"
authors = ["Oleksandr Besan <oleksandr.besan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
rich = "^10.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

